apiVersion: v1
kind: ConfigMap
metadata:
  name: confluence-env
  namespace: default
data:
  values.yaml: |  # This is the key that was missing and causing the error
    ignore_jvm_version: "true"
    COREY_VAR: "fuck"
    confluence:
      aaaaa: "huh"
      additionalJvmArgs:
        - -CDPSays=true
        - -ignore_jvm_version=true