apiVersion: v1
kind: ConfigMap
metadata:
  name: confluence-env
  namespace: default
data:
  values.yaml: |  # This is the key that was missing and causing the error
    confluence-env-config-map-var: "confluence-env-config-map-var-value"
    confluence:
      confluence_env-config-map-var: "confluence_env-config-map-var-value"
      additionalJvmArgs:
        - -ignore_jvm_version_from_additional_jvm_args=true
        - -ignore_jvm_version=true