apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: confluence
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: confluence
      version: 1.22.4
      sourceRef:
        kind: HelmRepository
        name: confluence
  valuesFrom:
    - name: confluence-env
      kind: ConfigMap
  # these values are going to cm: confluence-helm-values
  values:
    replicaCount: 1
    # additionalEnvironmentVariables:
    #   - name: cdp_idk_learning_this_chart
    #     value: "true"
    ingress:
      enabled: true
      hosts:
        - host: confluence.example.com
          paths:
            - path: /
              pathType: Prefix
