apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: confluence
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: confluence
      version: 1.22.4
      sourceRef:
        kind: HelmRepository
        name: confluence
  valuesFrom:
    - name: confluence-env
      kind: ConfigMap
  # these values are going to cm: confluence-helm-values
  values:
    confluence:
      additionalEnvironmentVariables:
        - name: "CoreyHelmLove"
          value: "Corey Loves Helm"
        - name: ignore_jvm_version
          value: "true"
    resources:
      jvm:
        maxHeap: "8192m"
        minHeap: "8192m"
        reservedCodeCache: "1024m"
    replicaCount: 1
    ingress:
      enabled: true
      hosts:
        - host: confluence.example.com
          paths:
            - path: /
              pathType: Prefix
